name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        agent: ['windows-latest','ubuntu-latest','macos-latest']
      
    runs-on: ${{matrix.agent}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ./function-app
      run: dotnet restore
    - name: Build
      working-directory: ./function-app
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./function-app
      run: dotnet test --no-restore --verbosity normal
